-- Script para criar sequences usadas pelas entidades (Oracle)
-- Execute como usuário com privilégios de criação de sequence

CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_RECOMENDACAO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_HABILIDADE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TAREFA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EMPRESA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

PROMPT Sequences criadas com sucesso.

